namespace Dx.Core;

/// <summary>
/// Represents a single entry in the session transaction log, as returned by
/// <see cref="DxRuntime.GetLog"/>.
/// </summary>
public sealed class LogEntry
{
    /// <summary>Gets or sets the auto-incremented log entry identifier.</summary>
    public int Id { get; set; }

    /// <summary>
    /// Gets or sets the direction of the transaction: <c>llm</c> for documents originating
    /// from a language model, or <c>tool</c> for documents generated by CLI tooling.
    /// </summary>
    public string Direction { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the snapshot handle produced by the transaction, or
    /// <see langword="null"/> when the transaction failed or produced no mutation.
    /// </summary>
    public string? SnapHandle { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the transaction succeeded (<c>1</c>) or
    /// failed (<c>0</c>).
    /// </summary>
    public int TxSuccess { get; set; }

    /// <summary>Gets or sets the ISO 8601 UTC timestamp at which the transaction was recorded.</summary>
    public string CreatedAt { get; set; } = string.Empty;

    /// <summary>Parameterless constructor required by Dapper for materialisation.</summary>
    public LogEntry() { }

    /// <summary>Initialises a fully validated <see cref="LogEntry"/> instance.</summary>
    public LogEntry(int id, string direction, string? snapHandle, int txSuccess, string createdAt)
    {
        if (string.IsNullOrWhiteSpace(direction))
            throw new ArgumentException("Direction cannot be null or empty.", nameof(direction));

        if (txSuccess != 0 && txSuccess != 1)
            throw new ArgumentOutOfRangeException(nameof(txSuccess), "TxSuccess must be either 0 or 1.");

        if (string.IsNullOrWhiteSpace(createdAt))
            throw new ArgumentException("CreatedAt cannot be null or empty.", nameof(createdAt));

        Id = id;
        Direction = direction;
        SnapHandle = snapHandle;
        TxSuccess = txSuccess;
        CreatedAt = createdAt;
    }
}
