# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: ulfbou.dxs
PackageVersion: 0.2.0
InstallerType: zip
Commands:
  - dxs
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ulfbou/dxs/releases/download/v0.2.0/dxs-0.2.0-win-x64.zip
    InstallerSha256: 0000000000000000000000000000000000000000000000000000000000000000
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: dxs.exe
        PortableCommandAlias: dxs
  - Architecture: arm64
    InstallerUrl: https://github.com/ulfbou/dxs/releases/download/v0.2.0/dxs-0.2.0-win-arm64.zip
    InstallerSha256: 0000000000000000000000000000000000000000000000000000000000000000
    NestedInstallerType: portable
    NestedInstallerFiles:
      - RelativeFilePath: dxs.exe
        PortableCommandAlias: dxs
ManifestType: installer
ManifestVersion: 1.6.0
